export const courses = [
  {
    id: 1,
    title: 'React Native',
    author: 'Hai Pham',
    level: 'Advance',
    released: 'May 6, 2020',
    duration: 30,
    averageRating: 4.4,
    totalRating: 200,
    urlImg: '',
  },
  {
    id: 2,
    title: 'Swift',
    author: 'Hai Pham',
    level: 'Advance',
    released: 'June 6, 2019',
    duration: 40,
    averageRating: 4.2,
    totalRating: 227,
    urlImg: '',
  },
  {
    id: 3,
    title: 'Android',
    author: 'Nguyen Cuong',
    level: 'Advance',
    released: 'June 5, 2019',
    duration: 40,
    averageRating: 4.8,
    totalRating: 600,
    urlImg: '',
  },
  {
    id: 4,
    title: 'Docker',
    author: 'Cuong Joker',
    level: 'Advance',
    released: 'June 5, 2020',
    duration: 40,
    averageRating: 4.2,
    totalRating: 700,
    urlImg: '',
  },
  {
    id: 5,
    title: 'Express Js',
    author: 'Nhu Daika',
    level: 'Advance',
    released: 'June 5, 2020',
    duration: 60,
    averageRating: 4.5,
    totalRating: 1200,
    urlImg: '',
  },
  {
    id: 6,
    title: 'Node Js',
    author: 'Hai pham',
    level: 'Advance',
    released: 'May 2, 2020',
    duration: 40,
    averageRating: 4.2,
    totalRating: 589,
    urlImg: '',
  },
];

export const authors = [
  {
    name: 'Cristiano Ronaldo',
    intro: '',
    urlAvatar: require('../../assets/images/cristiano-ronaldo.jpg'),
  },
  {
    name: 'Barack Obamaa',
    intro: '',
    urlAvatar: require('../../assets/images/barack-obama.jpg'),
  },
  {
    name: 'Taylor Swift',
    intro: '',
    urlAvatar: require('../../assets/images/taylor-swift.jpg'),
  },
  {
    name: 'Kaká',
    intro: '',
    urlAvatar: require('../../assets/images/kaka.jpg'),
  },
  {
    name: 'John Boyds',
    intro: '',
    urlAvatar: require('../../assets/images/john-boyd.jpg'),
  },
];

export const paths = [
  {
    id: 1,
    title: 'React Native',
    numberCourses: 12,
    duration: 30,
    averageRating: 4.2,
    urlImg: '',
  },
  {
    id: 2,
    title: 'Swift',
    numberCourses: 16,
    duration: 50,
    urlImg: '',
  },
  {
    id: 3,
    title: 'Android',
    numberCourses: 12,
    duration: 30,
    averageRating: 4.2,
    urlImg: '',
  },
];
